package dev.drimoz.materialnexus.datapack;

import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.mojang.logging.LogUtils;
import net.minecraft.SharedConstants;
import net.minecraft.network.chat.Component;
import net.minecraft.server.packs.PackLocationInfo;
import net.minecraft.server.packs.PackSelectionConfig;
import net.minecraft.server.packs.PackType;
import net.minecraft.server.packs.PathPackResources;
import net.minecraft.server.packs.repository.Pack;
import net.minecraft.server.packs.repository.PackSource;
import net.neoforged.neoforge.event.AddPackFindersEvent;
import org.slf4j.Logger;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.Comparator;
import java.util.Map;
import java.util.Optional;
import java.util.stream.Stream;

/**
 * The generated datapack (ADR-007): build output in {@code config/materialnexus/generated/},
 * overwritten as a whole, injected into every world at the top of the pack list.
 */
public final class GeneratedPack {
    public static final String PACK_ID = "materialnexus_generated";
    /** Tags of the items created for missing forms (MNX-039), rebuilt from the registered items at every pack scan. */
    public static final String ITEMS_PACK_ID = "materialnexus_items";
    public static final String MARKER = "_GENERATED_DO_NOT_EDIT";
    public static final String MANIFEST = "manifest.json";
    private static final Logger LOGGER = LogUtils.getLogger();

    private GeneratedPack() { }

    public static void onAddPackFinders(AddPackFindersEvent event) {
        if (event.getPackType() != PackType.SERVER_DATA) return;
        Path dir = MnxPaths.generated();
        Path items = MnxPaths.root().resolve("created_items");
        try {
            if (!isOurs(dir) || !isOurs(items)) {
                LOGGER.warn("{} or {} exists but was not created by Material Nexus; it is left untouched and not loaded", dir, items);
                return;
            }
            if (!Files.exists(dir.resolve(MARKER))) write(dir, Map.of(), new JsonArray());
            write(items, createdItemTags(), new JsonArray());
        } catch (IOException e) {
            LOGGER.error("Could not prepare the Material Nexus generated pack", e);
            return;
        }
        add(event, PACK_ID, dir);
        add(event, ITEMS_PACK_ID, items);
    }

    /** One convention tag file per created item's tag; the items are registered, so plain values. */
    private static Map<String, JsonElement> createdItemTags() {
        Map<String, JsonObject> files = new java.util.TreeMap<>();
        for (var item : dev.drimoz.materialnexus.registry.MnxItems.CREATED) {
            var tag = item.get().entry().tag();
            files.computeIfAbsent("data/" + tag.getNamespace() + "/tags/item/" + tag.getPath() + ".json", p -> {
                JsonObject file = new JsonObject();
                file.addProperty("replace", false);
                file.add("values", new JsonArray());
                return file;
            }).getAsJsonArray("values").add(item.getId().toString());
        }
        return Map.copyOf(files);
    }

    private static void add(AddPackFindersEvent event, String id, Path dir) {
        var info = new PackLocationInfo(id, Component.translatable("materialnexus.pack.generated"), PackSource.BUILT_IN, Optional.empty());
        Pack pack = Pack.readMetaAndCreate(info, new PathPackResources.PathResourcesSupplier(dir), PackType.SERVER_DATA,
                new PackSelectionConfig(true, Pack.Position.TOP, false));
        if (pack != null) event.addRepositorySource(consumer -> consumer.accept(pack));
    }

    /**
     * Replaces the whole pack with {@code files} (pack-relative path to JSON) and a manifest of
     * {@code changes}. Refuses to delete a folder Material Nexus did not create.
     */
    public static void write(Path dir, Map<String, JsonElement> files, JsonArray changes) throws IOException {
        if (!isOurs(dir)) throw new IOException("Refusing to overwrite " + dir + ": it has no " + MARKER + " marker");
        Path tmp = dir.resolveSibling(dir.getFileName() + ".tmp");
        deleteRecursively(tmp);
        Files.createDirectories(tmp);

        Files.writeString(tmp.resolve(MARKER), "Generated by Material Nexus from config/materialnexus/policies/. Edits here are overwritten.\n");
        writeJson(tmp.resolve("pack.mcmeta"), packMeta());
        JsonObject manifest = new JsonObject();
        manifest.addProperty("format", 1);
        manifest.add("changes", changes);
        writeJson(tmp.resolve(MANIFEST), manifest);
        for (var entry : files.entrySet()) {
            Path target = tmp.resolve(entry.getKey()).normalize();
            if (!target.startsWith(tmp)) throw new IOException("Generated path escapes the pack: " + entry.getKey());
            Files.createDirectories(target.getParent());
            writeJson(target, entry.getValue());
        }

        // ponytail: delete-then-move is not atomic; a crash in between leaves no pack, and the next
        // startup writes an empty one. Upgrade to a rename-swap if that window ever matters.
        deleteRecursively(dir);
        Files.move(tmp, dir);
    }

    /** True if MNX may manage this folder: absent, empty, or carrying our marker. */
    static boolean isOurs(Path dir) throws IOException {
        if (!Files.exists(dir) || Files.exists(dir.resolve(MARKER))) return true;
        try (Stream<Path> entries = Files.list(dir)) {
            return entries.findAny().isEmpty();
        }
    }

    private static JsonObject packMeta() {
        JsonObject description = new JsonObject();
        description.addProperty("translate", "materialnexus.pack.generated");
        JsonObject pack = new JsonObject();
        pack.add("description", description);
        pack.addProperty("pack_format", SharedConstants.getCurrentVersion().getPackVersion(PackType.SERVER_DATA));
        JsonObject root = new JsonObject();
        root.add("pack", pack);
        return root;
    }

    private static void writeJson(Path file, JsonElement json) throws IOException {
        Files.writeString(file, new GsonBuilder().setPrettyPrinting().create().toJson(json), StandardCharsets.UTF_8);
    }

    private static void deleteRecursively(Path dir) throws IOException {
        if (!Files.exists(dir)) return;
        try (Stream<Path> walk = Files.walk(dir)) {
            for (Path p : walk.sorted(Comparator.reverseOrder()).toList()) Files.delete(p);
        }
    }
}
